### ISSUE TITLE
MisterMenu Web Application: Initialize Project Checklist

### ISSUE THREAD

**Issue by jeffrymahbuubi** [mistermenu/mistermenu#2]
### Initialize Project Checklist

- [x] ESLint
- [x] Tailwind CSS
- [x] Prettier Tailwind CSS Plugin
- [x] ViteJS + React + Typescript
- [x] Axios Package
- [x] React Icon Package

### Recommendation Extension in VSCode
- ESLint
- Inline Fold
- Post CSS

**Comment by mistermenu4** [comment]
DONE
